### ISSUE TITLE
[Feature Request] Allow activity to specify backoff interval via failure

### ISSUE THREAD

**Issue by yiminc** [temporalio/features#442] opened 2024-03-27 02:37 UTC
### Is your feature request related to a problem? Please describe.

Allow activity to specify backoff interval for next retry when return failure. This is now supported by server https://github.com/temporalio/temporal/issues/1515

**Comment by cretz** [comment] 2024-03-27 13:43
Closing as a duplicate of https://github.com/temporalio/features/issues/419

**Closed by cretz** 2024-03-27 13:43 UTC
Labels: enhancement
