### ISSUE TITLE
Data conversion and encryption for Failures and Stacktrace Query results

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/features#74] opened 2022-07-19 15:57 UTC
1. We need to separate two concepts in SDK: data converter and encoder. These are two separate things and should be set explicitly differently. Data Converter is 'objects -> bytes'. Data Encoder is 'bytes -> bytes'.
2. Stacktrace query results and stacktraces of Temporal Failures should always be converter using a standard Temporal Data Converter. There is no reason to apply a custom user data converter for these text values that should be displayable in Temporal UI as easily as possible.
3. By default, Data Encoder is not applied to Stacktrace Query results and stacktraces of Temporal Failures. This is a reasonable default to allow users the easiest direct access to the failure information during investigations. 
4. Temporal SDK should provide an opt-in flag to apply Data Encrypter to stacktraces.
5. Everything said above is not applied for additional 'values' payload of Temporal Failures which is a piece of additional information that may be attached by users for propagation. This additional payload is a normal user object and should be processed by a custom user data converter and encrypted (or not) like any other regular Payload like an activity input parameter or result for example).

_This task will be updated with specific method names_

**Comment by lorensr** [comment] 2022-07-19 17:28
In ts/go/python, we use these terms:

- Payload Converter: `object -> bytes`
- Payload Codec: `bytes -> bytes` (can do encryption, compression, etc)
- Data Converter: tuple of (payloadConverter, single payloadCodec or list of payloadCodecs)

Docs:

https://docs.temporal.io/concepts/what-is-a-data-converter/#payload-codecs

**Comment by lorensr** [comment] 2022-07-19 18:47
> 4. Temporal SDK should provide an opt-in flag to apply Data Encrypter to stacktraces.

Maybe: 

```
WorkerOptions.applyCodecsToFailures
WorkerOptions.applyCodecsToStackTraceQueryResults
```

both default false.

> 5. Everything said above is not applied for additional 'values' payload of Temporal Failures

`details` and `last_heartbeat_details`:

https://github.com/temporalio/api/blob/c8a79e6cb7db277a3a990ee6d6118a77750e9f50/temporal/api/failure/v1/message.proto#L40-L60

**Comment by Spikhalskiy** [comment] 2023-03-07 21:30
Implemented in JavaSDK:
- [x] https://github.com/temporalio/sdk-java/pull/1330 PayloadCodec framework and abstraction
- [x] https://github.com/temporalio/sdk-java/pull/1645 Failure conversion / encryption
- [ ]  https://github.com/temporalio/sdk-java/issues/1586

**Comment by josh-berry** [comment] 2023-10-13 21:25
Possibly-dumb question, but how is this related to #66? Seems like (3) and (4) is exactly what #66 is asking for? Not sure about the data converter parts though—if I read the docs, I get the impression that these are the same thing, except Dmitry's point (1) seems to indicate they're different.

**Comment by cretz** [comment] 2023-10-13 21:46
I suspect this is essentially a duplicate of that one

**Comment by lorensr** [comment] 2023-10-13 21:53
I think dup, also a lot of this may have been implemented since these issues were opened

**Comment by josh-berry** [comment] 2023-10-13 22:20
Closing as dup of #66.

**Closed by josh-berry** 2023-10-13 22:20 UTC
Labels: enhancement
