### ISSUE TITLE
[Feature Request] Send SDK name and version on workflow task completion

### ISSUE THREAD

**Issue by bergundy** [temporalio/features#232] opened 2023-02-23 17:44 UTC
The information should be persisted in the `WorkflowTaskCompleted` event for debugging purposes.

Possibly, we'd use the [sdk_metadata](https://github.com/temporalio/api/blob/44e4397262d480b9e6f17771be9ae1812d97384e/temporal/api/history/v1/message.proto#L201) field to store this.

**Comment by cretz** [comment] 2023-02-23 17:50
Can you clarify the debugging purpose for adding this information to every task complete? Specifically, what are people unable to do today that this would enable? Is there concern a user does not know the SDK and version they are running under and/or we would be unwilling to ask for that if we are debugging?

**Comment by mfateev** [comment] 2023-02-23 18:05
For storage size reasons, we can send them only if they have changed since the previous workflow task. 

I believe knowing the exact SDK version might help in troubleshooting certain failure scenarios.

**Comment by Quinn-With-Two-Ns** [comment] 2024-01-10 14:17
Duplicate of  https://github.com/temporalio/features/issues/321

**Closed by Quinn-With-Two-Ns** 2024-01-10 14:17 UTC
Labels: enhancement
