### ISSUE TITLE
[Feature Request] Add an http header indicating temporal namespace for each request

### ISSUE THREAD

**Issue by underrun** [temporalio/features#86] opened 2022-07-21 22:51 UTC
### Is your feature request related to a problem? Please describe.

There are conditions under which it would be advantageous to make routing, balancing, rate limiting decisions on requests at L7 based on the namespace associated with the request. This is especially true for multitenant environments to manage QoS across many namespaces. Currently a workaround for this is to create DNS names per namespace that all point to the same temporal server and inject SNI info into the http header at the edge, but this can also get unmanageable at scale and requires coordinating creating a domain with registering a namespace which should ordinarily be a light weight operation.

### Describe the solution you'd like

Ideally, all requests from all SDKs would include an http header that indicates the temporal namespace the request is associated with. This leaves out operations that don't relate to a namespace, but as these are relatively few it shouldn't be an issue (or could be addressed in the future if it becomes a problem).

### Additional context

This can also be useful in the context of very large temporal services where namespaces are sharded across multiple temporal servers behind the same L7 loadbalancer but that do not require the SDK client to know which temporal server the namespace is hosted on.

**Comment by Quinn-With-Two-Ns** [comment] 2024-07-30 15:36
duplicate of https://github.com/temporalio/features/issues/475

**Closed by Quinn-With-Two-Ns** 2024-07-30 15:36 UTC
Labels: enhancement
