### ISSUE TITLE
[Feature Request] Allow SDKs to create Schedule specs from tctl json structure

### ISSUE THREAD

**Issue by XerxesDGreat** [temporalio/features#341] opened 2023-10-05 21:40 UTC
### Is your feature request related to a problem? Please describe.

In the documentation regarding [schedule specs](https://docs.temporal.io/workflows#spec), there is a sample json structure which can be used by tctl to schedule the running of workflows. By contrast, the SDKs (in particular, the Java SDK) require rigidly structured and often cumbersome operations to create the same. This discrepancy means that it is impossible to simply copy the configuration from one place and use it in another which makes development of schedule specs in different languages more risky.

Further, the fact that the method of defining a schedule spec requires construction of multiple objects in a very particular way means it's more difficult for a less technical person to define a schedule spec and considerably decreases the readability of the spec.

### Describe the solution you'd like

The proposal is to provide a method which accepts a json structure (as on the page linked above) and, from that, constructs a ScheduleSpec. This would allow for potential extraction of schedule definition to a config file, meaning source code doesn't need to be changed whilst making changes to a schedule. Further, one could copy the schedule spec from one application to another, even in a different language, and have confidence that the resulting runtime operates on the same schedule. This translation from json to schedule spec already happens in the `tctl` application; porting that logic to the other temporal libraries would be incredibly helpful.

**Comment by cretz** [comment] 2023-10-06 14:50
I believe this is a duplicate of #118. Can you confirm?

**Comment by XerxesDGreat** [comment] 2023-10-06 16:59
No, that's not a duplicate; that ticket is asking for being able to define schedules in code at all. What I would like is for the SDKs to have a method which accepts a json blob defining the calendar specification, the same type of blob specified in the docs linked above which is accepted by `tctl`. For example:

```
String json = """
{
  "year": "2022",
  "month": "Jan,Apr,Jul,Oct",
  "dayOfMonth": "1,15",
  "hour": "11-14"
}
"""
ScheduleSpec spec = ScheduleSpec.fromJson(json);
```

This would provide the ability to use _exactly_ the same specification (the json blob) in all the SDKs, ensuring consistency of schedules across the various languages. This also provides a much easier method for defining the schedule since the Java analog of the spec above looks like 
```
ScheduleCalendarSpec.Builder builder = ScheduleCalendarSpec.newBuilder()
  .setYear(listOf(ScheduleRange(2022)))
  .setMonth(listOf(ScheduleRange(1), ScheduleRange(4), ScheduleRange(7), ScheduleRange(10)))
  .setDayOfMonth(listOf(ScheduleRange(1), ScheduleRange(15)))
  .setHour(listOf(ScheduleRange(11,14)))
ScheduleSpec = ScheduleSpec.newBuilder()
  .setCalendars(listOf(builder.build())
  .build()
```
It is far harder to grok what is going on in that code which makes it more difficult and risky to add or change schedules, which is compounded by each of the SDKs having different ways of doing things. Introducing helper functions to make them as consistent with each other as possible leads to less risk of bugs and misconfiguration going forward.

**Comment by cretz** [comment] 2023-10-06 17:40
That aforementioned issue will be tracking the ability to create schedules from a declarative language like YAML/JSON (JSON is a bit rough for humans that may want to add comments and such). And it would be the same format across all SDKs/CLI and there will be SDK methods to use that declarative language to create/update schedules.

**Comment by cretz** [comment] 2023-10-06 19:15
:+1: I added clarification over there

**Closed by cretz** 2023-10-06 19:15 UTC
Labels: enhancement
