### ISSUE TITLE
[Feature Request] Expose AdminService api in sdks

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/features#348] opened 2023-10-12 00:04 UTC
https://github.com/temporalio/temporal/tree/main/api/adminservice

**Comment by cretz** [comment] 2023-10-12 12:32
We don't expose any internal server services in APIs. Temporal API that should be exposed in SDKs should be exposed via https://github.com/temporalio/api. If this service is one of those, it needs to be exposed out of the frontend via that repo.

Can we close this and if we want to expose more Temporal API we open a server issue to expose that via our normal API repo?

**Comment by darshan-au** [comment] 2023-10-18 20:05
@cretz: We are currently experiencing issues where workflow executions are stuck and not starting workflow task executions.
While we are still trying to root cause the problem, currently we are able to work around it by running `tctl admin wf refresh_tasks`. 
In order to automate this, we are requesting for the AdminService api to be exposed via the SDKs

**Comment by cretz** [comment] 2023-10-18 21:22
Our SDKs only support official API at https://github.com/temporalio/api, but that API is internal API that we happened to expose previously via our old `tctl` tool but not in our new `temporal` CLI tool intentionally.

I think the specific request here would be to expose the internal refresh task API to the public API. I will bring up with team and change title if needed.

**Comment by cretz** [comment] 2023-10-18 21:48
Ok, after discussion, we can't really expose these via SDK because they are server internal APIs. But if you need to access programmatically you can use the server as a library e.g. `import "go.temporal.io/server/api/adminservice/v1"` + `client := adminservice.NewAdminServiceClient(connection)`, or you can call the CLI programmatically, or you can generate the gRPC if you must.

**Closed by cretz** 2023-10-18 21:48 UTC
Labels: enhancement
